from git import Repo
import requests
import os

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

def commit_fix(repo_path, file, message):

    repo = Repo(repo_path)

    branch = "ai-fix-branch"

    repo.git.checkout("-b", branch)

    repo.git.add(file)

    repo.index.commit(message)

    repo.git.push("origin", branch)

    return branch


def create_pull_request(owner, repo, branch):

    url = f"https://api.github.com/repos/{owner}/{repo}/pulls"

    headers = {
        "Authorization": f"token {GITHUB_TOKEN}"
    }

    data = {
        "title": "AI Generated Fix",
        "body": "Automatically generated by GitFix AI",
        "head": branch,
        "base": "main"
    }

    response = requests.post(url, json=data, headers=headers)

    return response.json()